# Generated by Django 4.1.7 on 2023-03-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
    ]
